[theme]
primaryColor = "#0d47a1"
sidebarBackgroundColor = "#0b3c26"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f8f9fa"
# Επαναφέρουμε το κείμενο σε μαύρο για να φαίνεται παντού
textColor = "#31333F"

